server:
  port: 8083

spring:
  application:
    name: cause
  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sdl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cms-realm

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka