server:
  port: 0

spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: 1234

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka